version: "3.8"
services:
    app:
        build:
            context: ./dockerConfig
            dockerfile: Dockerfile
        restart: "always"
        container_name: template-tallstack
        ports:
          - "8030:80"
        volumes:
            - ./:/var/www/html/
        networks:
            - network-mysql

networks:
    network-mysql:
        external: true
        name: mysql_network-mysql

volumes:
    db_volume:
        external: true
